# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
fortify_sast_scanning:
  image: rsenden/fortify-vulnerability-exporter
  variables:
    export_config: "/config/FoDToGitLab.yml"
  script:
  - echo Script entry is required but not used
  when: manual
  allow_failure: true
  artifacts:
    reports:
      sast: gl-fortify-sast.json
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
