include: 
  - project: 'Fortify/gitlab-ci-templates'
    file: 'templates/fortify-sast-fod.yml'
    ref: 'initial-docs'

fortify-sast-fod:
  variables:
    FOD_NOTES: "Testing variable override from included job"
  allow_failure: true