include: 'https://gitlab.com/Fortify/gitlab-ci-templates/-/blob/initial-docs/templates/fortify-sast-fod.yml'

fortify-sast-fod:
  variables:
    FOD_NOTES: "Testing variable override from included job"
  allow_failure: true