fortify_sast_scanning:
  image: rsenden/fortify-vulnerability-exporter
  variables:
    export_from: fod 
    export_to: json.gitlab
    json_gitlab_output_file: ${CI_PROJECT_DIR}/gl-sast.json 
    fod_vulnerability_embed: details,recommendations
  script: 
  - echo Hello
  when: manual
  allow_failure: true
  artifacts:
    reports:
      sast: gl-sast.json
  